server:
  port: 8082

spring:
  application:
    name: myservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    password: root
    username: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.enn.model
  configuration:
    map-underscore-to-camel-case: true

