server:
  port: 8080 #\u670D\u52A1\u7AEF\u53E3


spring:
  application:
    name: myservice #\u670D\u52A1\u540D
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  #\u6570\u636E\u5E93\u9A71\u52A8\u5305
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    password: root
    username: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.enn.model        #\u6240\u6709model\u522B\u540D\u6240\u5728\u5305
  configuration:
    map-underscore-to-camel-case: true      # \u5F00\u542F\u9A7C\u5CF0\u6620\u5C04

